# Generated by Django 3.0.6 on 2021-05-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_group', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('evolution_order', models.PositiveSmallIntegerField()),
                ('evolution_remaining', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseStats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('base_stat', models.PositiveSmallIntegerField()),
                ('effort', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapi.Pokemon')),
            ],
        ),
    ]
